### PR TITLE
Add iacas_uri to mso_mdoc issuer metadata

### LINKED ISSUE #62: IACA Metadata for Credential Issuers
This issue proposes an extension to OpenID4VCI Credential Issuer Metadata to publish Issuing Authority Certificate Authority (IACA) certificates.  These certificates are defined in ISO 18013-5 (mDL).

A key decision is whether to provide the certificates by value in the Credential Issuer Metadata itself or whether to provide it by reference at a different URI.  I propose to provide it by reference so that the timing of updates can be controlled by normal Web Cache-Control directives.  (This is the same reason that `jwks_uri` is used in OpenID Connect OP metadata to provide keys by reference.)

I propose that IANA certificates be provided using this Credential Issuer Metadata element:

> `mdoc_iacas_uri`:  OPTIONAL. URL of the Credential Issuer’s IACA set document. This document contains the IACA certificates [ISO 18013-5] the used to validate signatures for issued mDOCs.

The referenced document has this structure:
> {"iacas":
  [
    {"certificate": "base64-encoded DER representation of IACA certificate"},
    …
  ]
}

The top-level structure is intentionally parallel to a JWK Set – which uses a `keys` element whose value is an array of JWKs.  The array elements are structures with a required `certificate` element, allowing other certificate metadata to be added to the structures, such as expiration time, as needed.

### PR DESCRIPTION
**Pull request by awoie**
Added iacas_uri to mso_mdoc issuer metadata. Fixes #62

### CODE REVIEW

**Review by selfissued — APPROVED** [review]

**Review by paulbastian — CHANGES_REQUESTED** [review]
The PR changes data in the authorization details data, I think this is not the correct way, either these things belong into Issuer metadata or the mdoc itself.

**Comment by peppelinux** [comment]
> The PR changes data in the authorization details data, I think this is not the correct way, either these things belong into Issuer metadata or the mdoc itself.

I'm in favor of having `iacas_uri` in the issuer metadata. 
I'm not in favor of having it in the mdoc cbor, since it would be too much self-referential for a single artifact.

**Comment by jogu** [comment]
I think we should close this for now and continue discussion on the issue - there's unanswered questions on the issue and not consensus about why this is needed.

**Comment by awoie** [comment]
> The PR changes data in the authorization details data, I think this is not the correct way, either these things belong into Issuer metadata or the mdoc itself.

In the mdoc, this is not possible because not allowed by ISO 18013-5. This PR adds the info to the issuer metadata, doesn't it?

**Comment by Sakurann** [comment]
closing for now, to consolidate the discussion to the issue, so that we can agree on the direction.

**Pull request closed without merging**
