### PR TITLE
Update Credential Offer example to use credential_configuration_ids instead of credentials

### PR DESCRIPTION
**Pull request by deshmukhrajvardhan**
Closes https://github.com/openid/OpenID4VCI/issues/348

### CODE REVIEW

**Review by jogu — APPROVED** [review]
Thanks Rajvardhan! LGTM.

**Comment by deshmukhrajvardhan** [comment]
Thanks Joseph! I'll go ahead and merge

**Comment by Sakurann** [comment]
@deshmukhrajvardhan we'll go over it in the next wg call, but it's only chairs who merge the PRs, and usually we require more than 3 approvals and wait minimum for a week before merging PRs. thank you.

**Comment by deshmukhrajvardhan** [comment]
Oops sorry about that @Sakurann

Let me know how I can help untangle this mistake.

For future scenarios would it be a good idea to have these guidelines pop up during PR creation?

E.g.
Can we create a PR template with these guidelines?
https://docs.github.com/en/enterprise-server@3.9/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by Sakurann** [comment]
@deshmukhrajvardhan the chairs decided not to revert the PR this time, so all good - thank you for doing the PR. Yes, we will consider creating a template with the guidelines - thank you for the suggestion.

**Comment by Sakurann** [comment]
@deshmukhrajvardhan that would be great! would be happy to review if you could start drafting a template.

**Comment by deshmukhrajvardhan** [comment]
@Sakurann Here is a draft PR for it :)
https://github.com/openid/OpenID4VCI/pull/363

**Pull request merged**
